[package]
name = "boolean-func-rs"
version = "0.1.0"
authors = ["Simon Kirillov <svkirillov3@gmail.com>"]
edition = "2018"
license = "MIT"

[[bin]]
name = "main"
path = "src/main.rs"

[workspace]
members = [
    "lib/bool-func"
]

[dependencies]
bool-func = { path = "lib/bool-func" }
